### ISSUE TITLE
Support for Jakarta 2

### ISSUE THREAD

**Issue by gbataille** [blockwatch-cc/tzgo#20]
Hi all,

is anyone already working on that?
I'll start looking into upgrading our client this week. in particular, from the upgrade notes
- `consumed_gas` is deprecated and `consumed_milligas` should be used (parsed and exposed) instead
- the deprecated `big_map_diff` is removed

The rest seems to concern votes, which might not be in the scope of tzgo (have not checked)
If nobody has started, I'll see if I'm able to do it

**Comment by echa** [comment]
Hi,

the current master branch contains most Jakarta changes already (not version tagged, but soon).

What's already there

- new hash and address types
- protocol parameters
- new Michelson opcodes
- bigmap -> lazy diff (see `func (r OperationResult) BigmapEvents()`)

What's coming

- rollup operation parameter parsing in the RPC lib

The `consumed_gas` deprecation is an announcement, will go away in K or L. 

Is there anything else that you need?

**Comment by gbataille** [comment]
ah ok, I had not tried to browse the commits, just used the tags and was looking for `consumed_milligas`

Nope, nothing else. I wanted to do the `consumed_gas` thing in advance to be ready for when the field actually goes away. Not a high priority anyway. I'll put that on the side and if I come to it, I'll try to send a PR your way

(what I'm doing on my side is keeping both fields `ConsumedGas` and `ConsumedMilliGas` for backward compatibility but I want to derive the old `ConsumedGas` from the new `ConsumedMilliGas` so that when it disappears, it'll be a non-event)

**Comment by echa** [comment]
Then let me add two function wrappers that return gas and milligas no matter which fields are populated. It's not a big deal.

**Comment by echa** [comment]
Ok, its in the recent master branch. LMK if this is useful to you?

**Comment by gbataille** [comment]
awesome. that looks like what I was doing on my side. thanks for the quick turnaround
