### ISSUE TITLE
Create new release tag for Kathmandu support?

### ISSUE THREAD

**Issue by symtor** [blockwatch-cc/tzgo#25]
Hello,

I was wondering whether support of the Kathmandu proposal would merit a new release version (`v0.14.0` to honor the proposal number? :slightly_smiling_face: ). Or are there still features pending?

Thank you!

**Comment by echa** [comment]
Yes, soon. Calling on-chain views is in progress and codec support for the new increase_storage_paid call.

**Comment by 100mll** [comment]
Still in progress? 3 days to kathmandu on mainnet...

**Comment by echa** [comment]
Yeah, not gonna have time for the missing features, but TzGo works well without them. Will add at a later point.

**Comment by 100mll** [comment]
Can u pls bump new tag with my fix @echa?

**Comment by echa** [comment]
Sure. Done.
