### ISSUE TITLE
what is the workaround if we are still using the deleted methods in params?

### ISSUE THREAD

**Issue by SimonZxw777** [blockwatch-cc/tzgo#39]
In the new release of tzgo, we realized that you have deleted `CycleFromHeight `, `IsCycleStart`, `CycleStartHeight` , `CycleEndHeight` ,`SnapshotBlock` methods. But our service still relies on these 5 methods for collecting rewards and fees.

Any supports you guys can provide to solve this issue? Thank you !

**Comment by echa** [comment]
Hi, we were not aware of outside users of this quirky feature and removed the methods to lower maintenance costs and make TzGo compatible with new testnets / private networks. The functions require a database of protocol activations (start blocks, start cycles and protocol bugs) for each network which so far was hard-coded as this info is not available from the RPC. A refactored implementation is part of our new TzIndex release which is currently available as PRO subscription.

I see 2 alternatives: 
(1) We port our refactored implementation back to TzGo and add some extra code for managing the protocol activation list (either hard coded or loadable from file/config).
(2) You make a private fork of TzGo v1.15 and update the old hard-coded database yourself.

A1 will change the interface though, as most functions are based on info found in block headers now. This means you can no longer query the Params struct for an arbitrary block level or cycle outside the relevant protocol's range and you need a block header to start from. Both shouldn't be show stoppers, but require an RPC call and an archive node in comparison to v1.15.

Please note TzGo maintenance is currently on a best effort basis and our commercial projects have priority.

**Comment by xiaoxiaff** [comment]
Hi @echa! We have a draft PR and it should be able to cover what we need. We can use our private repo but would love to get some eyes from you! We are also connecting with the Tezos team to double verify it! Thanks!

**Comment by echa** [comment]
Thanks, I had a look but it doesn't make me happy because who's gonna support it in this form? Anyways, you touched my heart. I sat down tonight and implemented a new version based on a cleaner logic backported from the new TzIndex release. Its available as v1.16.4. Give it a try and let me know how it works for you.

**Comment by xiaoxiaff** [comment]
Thanks @echa! Yeah this is our temporary solution to make sure we can have smooth transition. Thanks so much for the helps! We will integrate with the new release instead. Thanks again!
