### ISSUE TITLE
Any reason why Ghost and Mumbai params are the same?

### ISSUE THREAD

**Issue by SimonZxw777** [blockwatch-cc/tzgo#41]
Hi!
Params for Mumbai: https://github.com/blockwatch-cc/tzgo/blob/master/tezos/params.go#L55
Params for Ghost: https://github.com/blockwatch-cc/tzgo/blob/master/tezos/params.go#L35
They are the same, what is the reason of it? Or it is a typo?

**Comment by echa** [comment]
They are actually the same.
