### ISSUE TITLE
Is it possible to make a call for @sp.onchain_view()

### ISSUE THREAD

**Issue by alex-semenyuk** [blockwatch-cc/tzgo#56]
@echa 
Is it possible to make a call for [@sp.onchain_view()](https://legacy.smartpy.io/docs/general/views) currently?

Thanks.

**Comment by echa** [comment]
Yes, the canonical way to create call stubs via `cmd/tzgen` and then call the auto-generated view method. You can also do it manually if you know how to produce the input arguments as `micheline.Prim` tree.

```go
// create a RPC client instance
cli, err := rpc.NewClient("https://rpc.tzpro.io", nil)

// you need a tezos.Address
addr, err := tezos.ParseAddress("KT1...")

// create a contract abstraction
c := contract.NewContract(addr, cli)

// construct your call args using (see micheline/builder.go for helpers)
var args micheline.Prim

// execute on-chain view with args
prim, err := con.RunView(ctx, "viewName", args)
```

**Comment by alex-semenyuk** [comment]
Thanks for hint, @echa 

I tried with simple view without args something like this

```
@sp.module
def main():
    class SimpleStorage(sp.Contract):
        def __init__(self, val):
            self.data.storedValue = val

        @sp.onchain_view()
        def simple_view(self):
            return self.data.storedValue 
```


called as above

```
var args micheline.Prim
prim, err := con.RunView(ctx, "simple_view", args)
```

but got 
<img width="545" alt="Screenshot 2024-01-03 at 00 06 08" src="https://github.com/blockwatch-cc/tzgo/assets/5480441/b3b18265-5974-4dd1-9dc6-afce6e4f0b1f">

<img width="548" alt="Screenshot 2024-01-03 at 00 07 30" src="https://github.com/blockwatch-cc/tzgo/assets/5480441/50b80a6c-d4ee-418e-b0e3-8f95c2dce23f">


it seems args should be somehow initialized?

**Comment by echa** [comment]
Try to give the view a single argument of type `unit`. When you call it, use `micheline.NewCode(micheline.D_UNIT)` as argument. I think the issue is that entrypoints/views cannot have an empty parameter list.
