### ISSUE TITLE
hi, How to create a private key and address?

### ISSUE THREAD

**Issue by ygcool** [blockwatch-cc/tzgo#7]
hi, How to create a private key and address?

and, How to sign a transaction with a private key? Then send

thank you

**Comment by echa** [comment]
We're working in version 2 of tzgo where all this will become available. Meanwhile please use any of the other great Tezos libraries like https://github.com/ecadlabs/taquito

**Comment by ygcool** [comment]
> We're working in version 2 of tzgo where all this will become available. Meanwhile please use any of the other great Tezos libraries like https://github.com/ecadlabs/taquito

Great, when will version 2 be available?

**Comment by echa** [comment]
Just published a new branch https://github.com/blockwatch-cc/tzgo/tree/feat/signing-and-broadcast to track progress for the upcoming release. For key management please have a look at `tezos/key.go`. Now you can generate, encrypt, decrypt and use all supported key types.

**Comment by echa** [comment]
Support just landed in master. Closing this ticket for now. Please feel free to reopen if you have further questions.
