### ISSUE TITLE
Monitor for new blocks

### ISSUE THREAD

**Issue by utdrmac** [blockwatch-cc/tzgo#8]
I'm looking at the example for rpc.NewBlockHeaderMonitor() in the README, and also digging through the code. How does the example handle the RPC timing out or closing unexpectedly? Do you have to wrap the entire example in an outer for loop to make it attempt to reconnect?

**Comment by echa** [comment]
The simplest example is here https://github.com/blockwatch-cc/tzgo/blob/master/examples/rpc.go#L228

And this is how we use monitor in TzIndex where we detect and handle all kinds of error situations and shutdown: https://github.com/blockwatch-cc/tzindex/blob/master/etl/crawler.go#L462

TzIndex configures a custom http.Client that gets all kinds of timeouts and connection parameters set here https://github.com/blockwatch-cc/tzindex/blob/master/cmd/tzindex/common.go#L201

**Comment by utdrmac** [comment]
I don't see anywhere in your code where timeouts are created/checked. In the code I'm writing, modeled after yours, I  experienced a 6min gap yesterday.

```
INFO[2021-10-08T07:04:55Z] New Block                                     Hash=BLrM6Ny5JNd7zFJ9kBZ3Fh2MzXnZ8vhiBs3v4ju4L75g9m4ydYA Level=70423 Timestamp="2021-10-08 07:04:52 +0000 UTC"
ERRO[2021-10-08T07:10:02Z] Error Decoding Block                          error="read tcp 10.8.3.6:37016->104.206.108.82:80: read: connection timed out"
INFO[2021-10-08T07:10:02Z] Starting listener...
INFO[2021-10-08T07:10:02Z] New Block                                     Hash=BL5voQWHL2R63v1RS3waSoSw7LeFiucqi39t9yirvbyof2bSyf5 Level=70440 Timestamp="2021-10-08 07:09:53 +0000 UTC"
```

How can you select {} on both mon.Recv() and a context timeout? Or is this being handled elsewhere that I'm not seeing?

**Comment by echa** [comment]
Following up although this has been stale for a while. Hope its still useful. 

To add an additional timeout you can use a timeout context when waiting for new blocks. Note the monitor becomes unusable when an error occurs, so you have to create a new monitor each time.

```go
var mon *rpc.BlockMonitor
ctx := context.Background()
for {
    if mon == nil {
        mon = rpc.NewBlockHeaderMonitor()
        err := c.MonitorBlockHeader(ctx, mon)
        if err != nil {
            // handle setup error
        }
    }
    ctx2, cancel := context.WithTimeout(ctx, time.Minute)
    block, err := mon.Recv(ctx2)
    if err != nil {
        if err == context.DeadlineExceeded {
          // do smth
        }
        cancel()
        mon = nil
        continue
    }
    // handle result here
}
```

Feel free to reopen if that's not what you need.
