### ISSUE TITLE
Interact with Smart contract

### ISSUE THREAD

**Issue by faragos** [blockwatch-cc/tzgo#9]
Hey nice library 🙂 
Is there a way how I can call a function on a smart contract with this library?
Could you please provide me a simple example?

**Comment by os2357** [comment]
Hi Marco,

smart contract support is currently under development as part of TzGo v2 and ready for public release by end of year, including smart contract call parameter and entrypoint encoding wrappers (from Go structs to Micheline encoded data), contract interface type-check helpers, off-chain view entrypoint call support, and view data en/decoding. We'll provide extensive documentation and hands-on coding examples.

**Comment by gdsoumya** [comment]
Hi @os2357 any update on this?

**Comment by echa** [comment]
Just pushed a new branch https://github.com/blockwatch-cc/tzgo/tree/feat/signing-and-broadcast to track progress. All the low-level functions to create, sign and send transaction including contract calls are there. An example program is under `examples/tx.go`. Documentation is coming soon.

Please share you're thoughts and opinion. High-level interface is still in flux (i.e. we'll be adding Signer and Wallet interfaces soon as well as convenience methods to convert Go types to Micheline parameter trees).

**Comment by gdsoumya** [comment]
Hi @echa the changes look pretty good, not sure if it's already there but would be great if it is possible to populate the account counter and estimate fees, storage and gas automatically to provide sane defaults (which users can override if needed). These would really make tzgo really simple and easy to use.

**Comment by echa** [comment]
Yes, duly noted. It's already on the todo list and coming very soon.

**Comment by echa** [comment]
Closing this ticket for now. Please feel free to reopen if you have further questions.
